### ISSUE TITLE
Create UI Mockup for Game Session Tracking

### ISSUE THREAD

**Issue by luigibesani** [DnD-Montreal/session-tome#126]
Create design mockups for game session tracking.
UI Interactive Mockup link:
- [Character Entry](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=682%3A30874&show-proto-sidebar=1)
- [DM Entry](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=682%3A26692&show-proto-sidebar=1)

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/126?planning-poker) with ZenHub @pascwhale
