### ISSUE TITLE
Scope Entry index to current user

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#145]
## Description
Currently the Entry index() function returns all items for all characters. Instead items returned should be scoped either to a specific the character we care about, or alternatively to the currently auth'd user.

## Possible Implementation
Change the query in the EntryController index() function to accept a query parameter, "character_id", in the request. if it is null, the scope to the Auth::user().

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/145?planning-poker) with ZenHub @JasonGadoury @pascwhale @RobertoNittolo

**Comment by m-triassi** [comment]
Looks like the estimates for this are 50/50, lets over estimate, just in case on this one
