### ISSUE TITLE
Accept: Explore Characters

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#157]
## Description
Acceptance Test for #34 
Character visibility functionality for player characters.

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

## Acceptance flow
1. User logs in
2. User modifies one of their existing characters to be public
3. User can share the link to their character with other users
4. User can view public characters when supplied with their link
5. User can set their character to private, making it no longer visible to other users

**Comment by DndMtl** [comment]
This feature worked perfectly!

-Kate Ruscito
