### ISSUE TITLE
Accept: Character Log Migrator

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#158]
## Description
Acceptance Test for #35
The ability to import characters from third party systems

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

## Acceptance flow
1. User logs in
2. User clicks the Import button
3. User supplies an https://www.adventurersleaguelog.com/ CSV file
4. User is redirected to a page with their newly created character, containing the details from the CSV
5. User Navigates back to the character index again
6. User clicks import again, and supplies a link to a public D&D Beyond character
7. User is redirected to a character page containing the details of their character from D&D Beyond

**Comment by DndMtl** [comment]
Character imports from DNDBeyond (DDB) and AdventureLeagueLog (ALL) are flawless. 

Suggestions: 
- In terms of UX, I would split the ALL and the DDB sections as it was super confusing which button I had to click once the CSV file was uploaded. I had to scroll past the DNDBeyond section and the IMPORT button looks like it belongs to the DNDBeyond section.


-Kate Ruscito

**Comment by m-triassi** [comment]
@pascwhale before i close this i just want to make sure you see that comment about changing up the designs, should be something we look into
