### ISSUE TITLE
Modify Rating Model

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#205]
## Description

Rating model should be modified to accommodate Rating System requirements as outlined by stakeholders. Ratings should be able to be of a predefined set of types. (such as "helpful", "creative, "accommodating", "negative", etc...)
More details to be added upon stakeholder's response. 

## Possible Implementation

Depending on number of rating types per rating instance, can either have a simple 'type' column added on to the model with a predefined constant set of types, or, if multiple types per rating are required, consider using a [bitmask](https://aaronfrancis.com/2021/bitmasking-in-laravel-and-mysql) implementation to handle the typing.

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/205?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo

**Comment by m-triassi** [comment]
This is definitely something we should discuss with @DndMtl, but until then, they did supply me with this survey a while ago that could be a starting point: 
![image](https://user-images.githubusercontent.com/9440691/144731195-bcafd317-29b2-4c14-a987-46fd42f9e517.png)

**Comment by IanjhPhillips** [comment]
[mock up](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=941%3A32375&scaling=scale-down&starting-point-node-id=682%3A30874&show-proto-sidebar=1) showing the different rating categories we've settled on.
