### ISSUE TITLE
Attach ratings to GMs upon entry creation

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#206]
## Description

Players should be able to create and attach ratings to entries and have that ratings be associated to the GM corresponding to the entry. 
Players should have the option to add a rating on either creation or editing of an entry.

## Possible Implementation

Use an action to implement creation of ratings and attaching them to an entry, similar to the Item Entry creation action

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/206?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo
