### ISSUE TITLE
Filter Rating Index

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#207]
## Description

Users should be able to view a list of GMs by their ratings and filter through that list according to the ratings that matter more to them. 

## Possible Implementation

Modify the index function on the Rating controller to take in a set of filters corresponding to rating type and only return ratings that fit the filter specified by the user.

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/207?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo

**Comment by m-triassi** [comment]
for this task we actually want to be able to sort the index by a particular rating "score" @bcobo341 you'll need to do the following, in broad terms:

1. add an accessor to users to calculate their "total" / "global" score
2. in the index function, fetch all the users, and then sort them by that any of the individual scores (creative, flexible, etc)
3. return that data

you also need to be able to sort by the language they DM in, to do that
1. you'll need to add language to the sessions model (add migration, add language to $fillable, check tests still pass, adjust factories, maybe also the request validators)
2. accept a request param to decide what to sort by,
3. do a query on users that checks the language of sessions they DM in (you could also make an accessor for this if you'd like)
4. return the sorted data

**Comment by m-triassi** [comment]
Almost forgot, you'll also need to do a fuzzy search by the user's name, so something like `User::where('name', 'like', '%{$variable}%')->...`
