### ISSUE TITLE
Add missing fields to entry form

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#211]
## Description

Some fields on the design mockups for DM entry creation are missing from the implementation.
Both details and magic items pages are missing components from the design mockup. These should be added.

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/211?planning-poker) with ZenHub @bcobo341

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/211?planning-poker) with ZenHub @pascwhale @AnnieTran13 @luigibesani
