### ISSUE TITLE
Character Detail Entry Form

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#215]
## Description

The user creates a new entry for their character from the Character Details page.

## Possible Implementation

Reuse DM Entry form with some different fields and the additional rating step.

## Additional Resources
[Mockups](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=682%3A30874&show-proto-sidebar=1)

**Comment by pascwhale** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/215?planning-poker) with ZenHub @AnnieTran13 @luigibesani @willyyhuang

**Comment by m-triassi** [comment]
dont forget the button! :) 
<img width="830" alt="entry_button_hello" src="https://user-images.githubusercontent.com/9440691/149040016-d4d59fa3-b629-4831-9e50-afe4a038495b.png">
