### ISSUE TITLE
Add Log Table to Character Details Page

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#217]
## Description

The user should be able to see a table of logs attached to their character on the character's details page.

## Expected Behavior

The user should be able to see a table of logs attached to their character on the character's details page.

## Actual Behavior

The user does not see a table of logs attached to their character on the character's details page.

## Steps to Reproduce

1.  Open character details page.
2.  Notice missing table

## Possible Fix

# Other

**Comment by m-triassi** [comment]
This seems to be a copy of #194, Closing
