### ISSUE TITLE
Create Mockups for Player Rating System

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#218]
## Description

Create mockups for player rating system.

## Possible Implementation

The character entry form should have a new step where the player selects the skills their game master showed.
The user should also see all the ratings of public GMs in the ratings tab.

## Links to Mockups
- [Ratings Table](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=942%3A33312&show-proto-sidebar=1)
- [Entry Form with Rating Step](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=682%3A30874&show-proto-sidebar=1)

**Comment by m-triassi** [comment]
We've all reviewed these by this point, this can be closed :)
