### ISSUE TITLE
Bulk Entry Creation Mock-ups

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#244]
## Description

Users should have the ability to create many entries for a character over a specific time period. _ie_: a player has played the same adventure for the past 4 weeks every week. they should be able to stub out entries for all 4 of those play session. 

The dialog should accept a start date, an end date, an interval / frequency, and an adventure played (nullable).
(the back-end is implemented and expects this see `BulkEntryController.php`)

## Possible Implementation

This could be expressed as a modal that pops up when pressing a button, or it can be an alternate flow in the entry create form.

## Out of scope

N/A

## Requirements / Restrictions

N/A

## Link to Mockups
[Bulk Entry Creation](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=1106%3A30876&show-proto-sidebar=1)

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/244?planning-poker) with ZenHub @pascwhale @willyyhuang

**Comment by pascwhale** [comment]
No changes were requested for these. I'll go ahead and close the issue.
