### ISSUE TITLE
Bulk Game / Character Entry Creation Component

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#245]
## Description

Implement Form / Modal for #244. Fill out details upon completion
Feature will involve some kind of modal or form that allows a user to enter 2 dates (start and end), a frequency (how many times per week), and, optionally an adventure, will post to the `entry-bulk.store` route

## Requirements / Restrictions

Requires #244 to be completed...

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/245?planning-poker) with ZenHub @AnnieTran13 @luigibesani @pascwhale @willyyhuang

**Comment by willyyhuang** [comment]
@pascwhale once you finished the design mock up, process who has time to do this and assign to them
