### ISSUE TITLE
Magic item column bug in character detail entry table

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#258]
i don't this this works. `value.items` is an array, so wouldn't you have to iterate over each item in the array to create a chip for each item? 
Since you already have approval, you can go ahead and just open a bug that references this comment, and fix it this sprint.

_Originally posted by @m-triassi in https://github.com/DnD-Montreal/session-tome/pull/238#discussion_r781636705_

**Comment by m-triassi** [comment]
I'm going to mark this one as duplicate and we can use #273 instead since it has more information
