### ISSUE TITLE
Deleting an entry in the entry table does not work 

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#261]
## Description
Deleting an entry does not work in the character detail entry table 

## Expected Behavior
delete and bulk deletion should work for the character detail entry table 

## Actual Behavior
no deleting is happening when delete button is clicked

## Steps to Reproduce

1. Select an existing character to enter character detail page
2. Clicking delete icon on the table for an existing entry

**Comment by willyyhuang** [comment]
This has been fixed.
