### ISSUE TITLE
Bulk Entry Delete

### ISSUE THREAD

**Issue by bcobo341** [DnD-Montreal/session-tome#264]
## Description

Allow multiple entries to be deleted by entries id

## Possible Implementation

Accept an array of ids in the same way the character delete function does on the `CharacterController`

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/264?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo
