### ISSUE TITLE
Add Edit/Delete DM+Character Entry options from the Character Page

### ISSUE THREAD

**Issue by luigibesani** [DnD-Montreal/session-tome#268]
## Description
The character page should have buttons which allow the user to :
- Edit a DM Entry
- Delete a DM Entry
- Edit a Character Entry
- Delete a Character Entry

**Comment by m-triassi** [comment]
<img width="830" alt="entry_button_hello" src="https://user-images.githubusercontent.com/9440691/149038809-3b20be18-8590-44f0-a32f-96fb1a3b7e8d.png">
