### ISSUE TITLE
Dungeon/game master field should be an autocomplete field.

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#295]
## Description

When filling out an entry form, a user should be able to search the system for the DM that ran their game. 

## Expected Behavior

Typing the name of a DM should reveal a drop down of selections that are close the the query string, and allow the user to pick from that list. if a user picks a DM from this list then the user chosen should have their **id** passed in the form as `dungeon_master_id`, if no user is selected from the drop down, then they typed string should be passed as `dungeon_master`.

## Actual Behavior

The field currently only accepts the string representation of the dm's name and passes it as `dungeon_master`. The drop down select doesn't render, nor can a user have their ID passed as `dungeon_master_id`.

## Steps to Reproduce

1. Sign in to an account
2. Create a character
3. Create an entry for that character
4. Observe in the form that typing the name of a different user in the "game master" field has no effect.

## Additional Notes

It's been mentioned that we should the dungeon/game master field should be an autocomplete field. We will need to create another issue for that.

_Originally posted by @AnnieTran13 in https://github.com/DnD-Montreal/session-tome/pull/237#discussion_r787315392_

**Comment by willyyhuang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/295?planning-poker) with ZenHub @AnnieTran13 @pascwhale @m-triassi
