### ISSUE TITLE
Use sans-serif font for username at the top right corner of the page

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#303]
## Description

Some usernames will be hard to read with the decorative font.

**Comment by willyyhuang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/303?planning-poker) with ZenHub @AnnieTran13 @luigibesani @pascwhale
