### ISSUE TITLE
Entry form should skip rating step if the GM field is empty

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#308]
## Description

The entry form should not allow the user to go to the Rating step of the form if no GM was entered in the first step.

## Expected Behavior

The entry form should automatically skip the Rating step when moving on to the next step. The form should also go back to the first page when clicking on the `Previous` button on the third page if no GM is entered.

## Actual Behavior

The entry form is shown when hitting next despite the GM field being empty. 

## Steps to Reproduce

1. Open the Character Detail page.
2. Create an Entry.
3. Click next without entering a GM.

## Possible Fix

# Other

**Comment by willyyhuang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/308?planning-poker) with ZenHub @AnnieTran13 @luigibesani @pascwhale
