### ISSUE TITLE
Manage characters

### ISSUE THREAD

**Issue by luigibesani** [DnD-Montreal/session-tome#32]
## User story
As a player I should be able to list and manage all my characters, so I can keep track of my available play options

## Acceptance criteria
|#     |Given     |When     |Then|
|---|---|---|---|
|1     |I am a player     |I create a character     |it is added to my list of characters. |
|2     |I am a player     |I list my characters      | a list of my characters are displayed in a window.|
|3     |I am a player     |I update a character    | the character's features are modified. |
|4     |I am a player     |I delete a character    | the character is removed from my list of characters.|

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/32?planning-poker) with ZenHub @luigibesani @willyyhuang @IanjhPhillips

**Comment by m-triassi** [comment]
It was probably overly optimistic to think we were going to complete this story within this sprint, adding this to the next sprint
