### ISSUE TITLE
Item edit redirect not ideal for user flow

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#334]
## Description

Editing an item either redirects to the character index or DM entry index. This isn't ideal when the edit form is submitted from the item's own detail page.

## Expected Behavior

The user should stay on the item detail page.

## Actual Behavior

The user is redirected to the character index page when using the item detail page.

## Steps to Reproduce

1. Open an item's detail page.
2. Edit an item using the `UPDATE` button.
3. Click on the `Save` button.

## Possible Fix

A possible fix is to redirect the user to the page they were on before opening the form.

# Other

**Comment by willyyhuang** [comment]
This has been fixed
