### ISSUE TITLE
Accept: Magic Item Inventory Management

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#336]
## Description
Acceptance Test for #36 
Ability to read, update, and delete magic items belonging to a particular character

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #311 for automation of this flow

## Acceptance flow
1. User Logs in
2. User Navigates to a Character on the Character index
1. User views the Items owned by a character
2. User Select an item
3. User Clicks the edit button
4. User Changes the details of the item
5. User clicks save
6. User Observes there is a change in the item details
7. User clicks the Delete Button
8. User Observes the item is deleted

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
