### ISSUE TITLE
Accept: Manage Entries

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#337]
## Description
Acceptance Test for #106 
Ability to create, read, update, and delete entries belonging to a particular character

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #312 for automation of this flow

## Acceptance flow
1. User Logs in
2. User Navigates to the character index
3. User Chooses a character to add an entry for
4. User clicks the "entry" button
5. User fills out the form with the details of a game they played
6. User skips any secondary steps (ratings, item creation)
7. User observes an update in their characters data (levels / gold gained)
8. User picks an existing entry
9. User clicks the edit button and changes the details of an entry
10. User observes a change in their characters data
11. User Deletes an existing entry
12. User observes a change in their characters data

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
