### ISSUE TITLE
Accept: Item Entry Management

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#338]
## Description
Acceptance Test for #36 
Ability to create an entry which attaches a magic item to a particular character

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

see #313 for automation of this flow.

## Acceptance flow
1. User Logs in
2. User Navigates to a character 
3. User clicks Entry to add a new entry
4. User fills out required information for an entry
5. User skips to the "items" step in the form
6. User clicks "add item" and fills the details of said item in
7. User Observes that the item has been created and is attached to both the character and the entry

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
