### ISSUE TITLE
Accept: Bulk Entry Creation

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#339]
## Description
Acceptance Test for #36 
Ability to create a series of entries that span a chosen time frame and belong to a particular character

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #314 for automation of this flow.

## Acceptance flow
1. User Logs in
2. User Navigates to a character in the character index
3. User clicks Bulk Entries
4. User chooses a date range over which they'd like the entries to be created
5. User chooses a frequency, and adventure played
6. User clicks create
7. User Observes that a large amount of entries has been created for their character.

**Comment by DndMtl** [comment]
I love the clock feature so much.
Everything works perfectly! Approved!

-Kate Ruscito
