### ISSUE TITLE
Explore characters

### ISSUE THREAD

**Issue by luigibesani** [DnD-Montreal/session-tome#34]
## User story
As a player, I should be able to control who can view my individual characters, so I can share specific characters with appropriate parties during events

## Acceptance criteria
|#     |Given     |When     |Then|
|---|---|---|---|
|1     |I am a player |I modify my character's privacy settings | the ability for other users to view my character's log is modified.|
|2     |I am a player |I attempt to view the characters of others | their information is displayed to me based on the character's privacy settings.|

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/34?planning-poker) with ZenHub @IanjhPhillips @luigibesani @willyyhuang

**Comment by m-triassi** [comment]
Same deal as #32 adding this to the next sprint, overly optimistic assuming this would be done this sprint
