### ISSUE TITLE
Accept: Create DM Entries

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#340]
## Description
Acceptance Test for #111 
Ability to read, and create DM entries belonging to a particular user

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #315 for automation of this flow

## Acceptance flow
1. User Logs in
2. User Navigates to the character index
3. User clicks DM Entries button
4. User observes their list of existing DM entries 
5. User clicks Create
6. User Fills out the details of they entry opting to not attach the entry to a particular character
7. User clicks save
8. User Observes the entry has been created

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
