### ISSUE TITLE
Accept: Assign DM Entries to Characters

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#341]
## Description
Acceptance Test for #111 
Ability to read, and create DM entries belonging to a particular user

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #315 for automation of this flow

## Acceptance flow
1. User Logs in
2. User Navigates to the Character index
3. User clicks "DM Entries"
4. User chooses an existing DM entry (or opts to create a new one)
5. User assigns the entry to a chosen character and chooses a reward type 
6. User clicks save 
7. User observes the item / level up corresponding the the reward chosen on the character they assigned the entry too

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
