### ISSUE TITLE
Accept: Game Master Ratings

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#342]
## Description
Acceptance Test for #201  
Ability to read, and create entries with ratings about a particular user

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #317  for automation of this flow

## Acceptance flow
1. User Logs in
2. User Navigates to the character index and chooses a character
3. User creates a new Entry that has a Game masters name attached to it 
4. User clicks next and chooses the options that reflect the Game master's play styles
5. User clicks next and saves the entry
6. The rating for the GM is attached in the system

**Comment by DndMtl** [comment]
I love the icons used for the DM rating.
Everything works perfectly! Approved!

-Kate Ruscito
