### ISSUE TITLE
Saving after editing a DM entry removes the reward choice and assigned character

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#343]
## Description

After creating an entry with a reward choice selected and a character assigned, when we edit it, those fields will come back empty on the edit drawer. If you save your edits without editing those fields, the reward choice selected and the character assigned to that entry will be removed.

## Expected Behavior

When editing a DM entry, the edit drawer must show the reward choice selected and assigned character (if any) of that entry.

## Actual Behavior

When editing a DM entry, the edit drawer shows an empty field for the reward choice selected and assigned character (if any) of that entry. After saving without filling those fields, the reward choice selected and assigned character are removed.

## Steps to Reproduce

1. Go to the character's page, select DM entry.
2. Create a DM entry with a reward choice selected and a character assigned.
3. Edit the DM entry without touching the reward choice and the character assigned fields.
4. Click save.
5. The entry no longer has the reward choice and the character assigned it was initially selected/assigned

## Possible Fix

# Other

**Comment by willyyhuang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/343?planning-poker) with ZenHub @AnnieTran13 @luigibesani @pascwhale
