### ISSUE TITLE
Accept: Rating Lookup

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#344]
## Description
Acceptance Test for #202 
Ability to read, Ratings belonging to a particular user / DM

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #318 for automation of this flow

## Acceptance flow
1. User Logs in
2. User Navigates to the Rating index page 
3. User Observes that there is a list of users that is filterable by Event ratings / non event ratings

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
