### ISSUE TITLE
Accept: User Rating Reports

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#358]
## Description
Acceptance Test for #203

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #319 for automation of this flow

## Acceptance Flow

1. Log in to admin account
2. Navigate to admin panel at /admin
3. Navigate to the users page from the panel on the left
4. Click the Rating Report button
5. Check that you are given a CSV rating report

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
