### ISSUE TITLE
Magic Item Inventory Management

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#36]
## User story
As a player I should be able to manage which magic items my characters are currently holding so that I can have a finer control over which rewards I take from completing adventures.

## Narrative
As a player, I should be able to add, edit, and remove magic items from my character.

## Acceptance criteria

|#     |Given     |When     |Then|
|---|---|---|---|
|1     | I am a player    | I navigate to my characters magic items list    | I can see a list of the magic items that my character has  |
|3     | I am a player    | I delete a magic item from my character    | The item is deleted and the list updates to reflect the changes |
|4     | I am a player    | I edit a magic item from my character    | The item is updated and the list updates to reflect the changes |

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/36?planning-poker) with ZenHub @IanjhPhillips @luigibesani @willyyhuang
