### ISSUE TITLE
Accept: Admin Event Control

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#361]
## Description
Acceptance Test for #243

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #321 for automation of this flow

## Acceptance Flow

1. Log into the admin account
2. Navigate to the admin page via /admin
3. Navigate to the events page via the panel on the left
4. View the list of events
5. Delete a event by clicking on the trash icon on an event line
6. Click the Add Event button
7. Enter the event information
8. Click save
9. Check that your event was created
10. Click the edit button on a event line
11. Enter new information
12. Click save
13. Click the preview button on a event to view its contents

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
