### ISSUE TITLE
Accept: Event Reports

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#362]
## Description
Acceptance Test for #247

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #322 for automation of this flow

## Acceptance Flow

1. Log into the admin account
2. Navigate to the admin page via /admin
3. Navigate to the events page via the panel on the left
4. View the list of events
5. Click Generate Report on an event line
6. Check that you were given a csv report file corresponding to the event you chose

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
