### ISSUE TITLE
Design Campagin Join Form

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#369]
## Description
See #251 for narrative. 
There should be a form that allows users to join a campaign. It should have a field where the user can enter a campaign join code. This field can be prefilled if the user uses a join link. The page must show the characters a player can join as. It should also present the option to join as a GM instead. If a user chooses to join as a GM then they should not be able to choose a character

## Possible Implementation

N/A

## Out of scope

N/A

**Comment by IanjhPhillips** [comment]
Campagin

**Comment by pascwhale** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/369?planning-poker) with ZenHub @AnnieTran13 @luigibesani @willyyhuang
