### ISSUE TITLE
Campaign Creation /  Edit Screen

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#370]
## Description
There should be a form on which users can specify details about a campaign they'd like to create. They should be able to choose the adventure to run for the adventure, the custom title of the campaign, as well as  (optionally) the character they'd like to play in the campaign. If the a character is chosen, they are automatically not assigned as the GM. 

The same form can be used for edit. On the edit screen, there should be a button to regenerate the join code.

## Possible Implementation

N/A

## Out of scope

N/a

## Requirements / Restrictions

N/a

**Comment by pascwhale** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/370?planning-poker) with ZenHub @AnnieTran13 @luigibesani @willyyhuang
