### ISSUE TITLE
Event Index Screen

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#372]
## Description

Show a list of all events that are coming up. Should show the event title, location, potentially the description, as well as the league hosting it. A user should be able to view the details of an event and therefore list all of the available sessions for the event. The sessions should list the DM, the adventure being played for that session, as well as how many seats are taken / left out of the total as well as a "register" button if there are available spots

## Possible Implementation

N/a

## Out of scope

N/a

## Requirements / Restrictions

N/a

## Mockups
[Event Index](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=1275%3A36506&show-proto-sidebar=1)

**Comment by pascwhale** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/372?planning-poker) with ZenHub @AnnieTran13 @luigibesani @willyyhuang
