### ISSUE TITLE
Trade Editing and Fulfillment

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#378]
## Description
Modify the trade update endpoint to allow users to modify their trade info.
If a user modifies their trade after a number of offers have already been made, the offers must be removed from the trade.

Additionally, the edit endpoint should accept an item id and a status to indicate that a trade offer has been accepted by the user who originally listed the trade. The trade must be then set to closed and the items should be swapped. 

## Possible Implementation
It might be a good idea to create an action for swapping two items between characters.

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/378?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo

**Comment by m-triassi** [comment]
I think theres something to specify here, that if a user just updates the `description` or the `requested_items` fields there isn't any reason to clear out the existing offers

**Comment by m-triassi** [comment]
Oh i see what i mention above is handled by #377?
