### ISSUE TITLE
Creating Trade Offers

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#379]
## Description

Users should be able to offer their characters' items in response to a trade listing.

## Possible Implementation
We might need a TradeOffer controller with a store and edit function that takes the original trade as well as the offered item and attaches it to the trade's items() relationship (NOT the item() relation)

We could also first check if the item in question is part of any open trades before attaching it. to prevent a user from offering their item against multiple trades.

The create function would include all valid items that can be offered for a given trade.

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/379?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo

**Comment by m-triassi** [comment]
I actually think it would be fine to allow a user to offer the same item for multiple trades. As long as we delete all offers related to that item when it gets accepted there shouldn't be an issue :)
