### ISSUE TITLE
Trade Offer / Management Screen

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#380]
## Description
There should a screen for users to manage their open trades. The screen should list their items for trade and allow the user to view the items that have been offered in return. The screen should also allow the user to accept or deny any given trade. 

The screen will list all items for trade and allow the user to see the offers, which will be comprised of the item offered in return, a hyperlink to the character that currently owns the item (so the user can audit the character), as well as an accept/deny button.

## Possible Implementation

N/a

## Out of scope

N/a

## Requirements / Restrictions

N/a

## Mockups
- [Trade Create](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=1490%3A41935&show-proto-sidebar=1)
- [Trade Detail Owner](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=1490%3A42203&show-proto-sidebar=1)
- [Trade Detail Visitor](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=1490%3A43200&show-proto-sidebar=1)

**Comment by pascwhale** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/380?planning-poker) with ZenHub @AnnieTran13 @luigibesani @willyyhuang
