### ISSUE TITLE
Refactor Entry Item Editing

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#381]
## Description
When an entry that has items is edited, the items are deleted and remade. This could be a source of problems with item trading, and should be refactored so that items are not deleted when the entry is edited.

## Possible Implementation
One idea is to simply prevent an item or entry to be edited if the item has been traded. The request would return to the entry edit page with an error response code that can be displayed in some way by front end.

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/381?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo

**Comment by m-triassi** [comment]
This also might involve some front-end tinkering. The easiest way i can see this working is that front-end passes the item id with the entry data, so we know if `item_id` is present, then its an existing item, if not, then its new. Additionally if an item id isn't present but was before, then that means it was deleted. we can probably leverage `->sync()` to do all this, but we'd have to check if the relation supports is
