### ISSUE TITLE
Campaign index page

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#384]
## Description

Users should be able to see a list of all the campaigns they are registered in. This can be a table that lists the title of the campaign as well as the character, if any, they are using in the campaign. They should also be able to see the details of the campaign. This could include the entries that were generated as part of the campaign, among other things like campaign title, characters, etc...

**Comment by AnnieTran13** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/384?planning-poker) with ZenHub @luigibesani @pascwhale @willyyhuang

**Comment by willyyhuang** [comment]
Merged to feature branch, therefore closing this issue
