### ISSUE TITLE
Session Creation and Edit on Backpack Leads to Unauthorized Error

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#421]
## Description

Creating or editing a session on the admin panel does not work.

## Expected Behavior

The forms for creating and editing a session should redirect to the index table on the admin panel.

## Actual Behavior

A 403 Unauthorized error is shown after submitting the form.

## Steps to Reproduce

1. Log onto Backpack.
2. Open the Sessions tab.
3. Create or edit an existing session and hit the `Save and Back` button.

## Possible Fix

# Other

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/421?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo
