### ISSUE TITLE
DM/regular entry are not differentiated in character detail

### ISSUE THREAD

**Issue by willyyhuang** [DnD-Montreal/session-tome#428]
## Description

Character detail entry table does not differentiate regular and DM entries, we need to open different forms based on the type of the entry.

## Expected Behavior

If the entry is DM, open DM entry form
if the entry is regular, open regular entry form

## Actual Behavior

Only opens regular entry right now

**Comment by willyyhuang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/428?planning-poker) with ZenHub @AnnieTran13 @luigibesani @pascwhale

**Comment by JasonGadoury** [comment]
Oops I think I set the estimate for this by accident

**Comment by willyyhuang** [comment]
@luigibesani this will also require backend to give you `characters` for DM entry form
