### ISSUE TITLE
Campaign Kick Endpoint

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#432]
## Description

Campaign owner should be able to kick characters and their corresponding user from their campaign.
The campaign join code should also be  regenerated after a kick request is performed.

## Possible Implementation

Add a destroy function to the campaign registration controller which accepts an array of user ids and removes the user and their characters from the campaign.

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/432?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo

**Comment by m-triassi** [comment]
Might be good for it to optionally accept a character id, which is specified only kicks the 1 character, just a thought :)
