### ISSUE TITLE
Add extra Event model accessors

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#435]
## Description

There are a number of pieces of data that will need to be displayed on both the event index, as well as the event details page.
This data includes: 
- **Event** date (single date or range)
- Event Capacity (total seats available)
- Amount of registered users (# of session registrations)
- Total spots available for an event (sum of all open seats)

See images for usage / location

![image](https://user-images.githubusercontent.com/9440691/155045058-82bc39b6-ba1a-4949-80cc-cce701489073.png)
![image](https://user-images.githubusercontent.com/9440691/155045151-cf9c4b18-64bf-47b6-9e6f-7fe04b56bd6b.png)

## Possible Implementation

Add accessors to event for each of these items. add the added accessors to the `$appends` property on the `Event` Model.

- **Event** date --> pluck all start times from event sessions sorted by ascending, if it spans multiple days, generate a date range (Jan 1 - Jan 3), otherwise just return the day the sessions are on.
- Event Capacity --> pluck seats from event sessions, take sum
- Total spots available for event --> pluck open_seats accessor, take sum
- Amount of registered users --> subtract event capacity and available seats values

## Out of scope

N/a

## Requirements / Restrictions

N/a

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/435?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo
