### ISSUE TITLE
Add Event model filtering capabilities

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#436]
## Description

There are a number of filters for the event index. One that lists events the user is registered for, and one that searches for a specific event by either name, description, location, or adventures being played. 

![image](https://user-images.githubusercontent.com/9440691/155046114-6f2c483f-c2be-4af4-a478-1638a03fa649.png)

## Possible Implementation

- Add the filterable trait to Event for the title, description and location fields.
- Add a scope query to event for filtering events that the user is registered too, (whereHas 'session.characters' with user_id == Auth::id())
- Add  "is_registered" Accessor to event, returns true if user has atleast 1 character registered to the session, add this accessor to the `$appends` property on the model.

## Out of scope

N/A

## Requirements / Restrictions

N/A

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/436?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo
