### ISSUE TITLE
Filter EventController index results

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#437]
## Description

Enable the ability to filter the event index by either the event title, description, location, adventure title**s** or by events the user is currently registered for. 

![image](https://user-images.githubusercontent.com/9440691/155047059-cede9c2c-6e5d-4780-aa70-889b842f1b2b.png)

## Possible Implementation

- Use the scope Query and filterable functionality added in #436 to reduce the number of results returned. --> accept 1 search parameter for filtererable fields, 1 for the registered toggle.
- Add a call that will load the `league` relationship `->load('league')` on the event.

## Out of scope

N/A
## Requirements / Restrictions

N/A

**Comment by IanjhPhillips** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/437?planning-poker) with ZenHub @bcobo341 @JasonGadoury @m-triassi @RobertoNittolo
