### ISSUE TITLE
Cypress Tests for League Admin Event Control

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#439]
## Description

Write E2E Cypress tests for #363 League Admin Event Control.

## Possible Implementation

- View League Events
- Create a League Event
- Edit a League Event
- Delete a League Event

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/439?planning-poker) with ZenHub @pascwhale

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/439?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @luigibesani @willyyhuang
