### ISSUE TITLE
Cypress Tests for Player Event Registration

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#440]
## Description

Write E2E Cypress tests for #241 Player Event Registration.

## Possible Implementation

- View Event Sessions
- Register to an Event Session
- Unregister from an Event Session

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/440?planning-poker) with ZenHub @pascwhale

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/440?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @luigibesani @willyyhuang
