### ISSUE TITLE
Cypress Tests for Session Entry Automation

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#442]
## Description

Write E2E Cypress tests for #364 Session Entry Automation.

## Possible Implementation

- Check for automatic character entry for a player after session start time
- Check for GM entry for a GM after session start time

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/442?planning-poker) with ZenHub @pascwhale

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/442?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @luigibesani @willyyhuang

**Comment by m-triassi** [comment]
Due to the nature / functionality of this feature, it will be impossible to have an E2E test that runs for this without being flaky. I vote we close this issue.

**Comment by pascwhale** [comment]
I agree, this would be hard to test.
