### ISSUE TITLE
Cypress Tests for Campaign Creation and Modification

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#443]
## Description

Write E2E Cypress tests for #365 Campaign Creation and Modification.

## Possible Implementation

- Create a Campaign
- Edit a Campaign
- Generate a new invite code

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/443?planning-poker) with ZenHub @pascwhale

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/443?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @luigibesani @willyyhuang
