### ISSUE TITLE
Cypress Tests for Campaign Enrollment

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#444]
## Description

Write E2E Cypress tests for #251 Campaign Enrollment.

## Possible Implementation

- View list of participating campaigns
- Join a campaign
- Kick a user from a campaign

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/444?planning-poker) with ZenHub @pascwhale

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/444?planning-poker) with ZenHub @bcobo341 @JasonGadoury @luigibesani @willyyhuang @IanjhPhillips
