### ISSUE TITLE
Cypress Tests for Campaign Entry Creation

### ISSUE THREAD

**Issue by pascwhale** [DnD-Montreal/session-tome#445]
## Description

Write E2E Cypress tests for #252 Campaign Entry Creation.

## Possible Implementation

- Check creation of campaigns for other members

**Comment by willyyhuang** [comment]
Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/445?planning-poker) with ZenHub @pascwhale

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/445?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @luigibesani @willyyhuang
