### ISSUE TITLE
Campaign Details errors when user is DM

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#484]
## Description
When accessing a campaign's detail page that the current authorized user is a DM for, the page errors out, showing a white screen

## Expected Behavior

The campaign detail page should load as intended, regardless of if a user is the DM, or a Character

## Actual Behavior

The page errors out and a white screen is shown. Additionally this error is thrown in the console. 

![image](https://user-images.githubusercontent.com/9440691/157569650-cf47cab8-3b0f-465d-aa5c-3dd71e342bea.png)

## Steps to Reproduce

1. Navigate to the campaign index
2. Create a new Campaign without assigning a character
3. Attempt to view the campaign's details

## Possible Fix

`userCharacter`'s type should be nullable in the details page.

**Comment by willyyhuang** [comment]
Merged to feature branch, closing this
