### ISSUE TITLE
Campaign character assignment should be optional

### ISSUE THREAD

**Issue by willyyhuang** [DnD-Montreal/session-tome#485]
## Expected Behavior

When creating a campaign, character should be optional, meaning that the field can be left as `null`

## Actual Behavior

When creating a campaign, it is required.
When editing a campaign, leaving the field `null` will not result an error, rather updates the campaign successfully

## Steps to Reproduce
![image.png](https://images.zenhubusercontent.com/613680f135e989b6c2ced361/a4fcfef4-40dc-4ae7-a37d-26b4c5933f08)

**Comment by m-triassi** [comment]
Closed via #488
