### ISSUE TITLE
Duplicate campaign on index page when joining the same campaign with different character

### ISSUE THREAD

**Issue by willyyhuang** [DnD-Montreal/session-tome#486]
## Description

Registering the same campaign with different character will result duplicate entry in campaign index page

## Expected Behavior

Will show up as ONE entry when there are duplicates,
I am also not sure if it is allowed for multiple characters under the same owner to join the same campaign

## Actual Behavior

Duplicate entries in campaign index table

## Steps to Reproduce
![image.png](https://images.zenhubusercontent.com/613680f135e989b6c2ced361/ebdb1993-74ae-440d-88be-1f3e4b1db35b)

**Comment by m-triassi** [comment]
closed via #489
