### ISSUE TITLE
Edit assigned character to none does not work

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#499]
## Description

When you create a campaign with an assigned character, then try to edit your assigned character (either through campaign table or the updating through campaign details) to None. Your assigned character will still be there and not get unassigned.

## Expected Behavior

Editing a campaign and selecting None for assigned character, after assigning a character, will not unassign the character.

## Actual Behavior

Editing a campaign and selecting None for assigned character, after assigning a character, will unassign the character and remove them from the campaign.

## Steps to Reproduce

1. Create a campaign and assign a character (not None)
2. Edit the campaign and select None for assigned character
3. Save
4. Character is not unassigned

## Possible Fix

# Other

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/499?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo
