### ISSUE TITLE
Incorrect redirects after creating entry or DM entry

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#500]
## Description

- In the campaign details page, there is a entry button in order to create an entry. After clicking on it, filling the entry form and clicking create, the user is incorrectly redirected to the (assigned)character's detail page.
- In the campaign details page, there is a DM entry button in order to create an entry. After clicking on it, filling the DM entry form and clicking create, the user is incorrectly redirected to the DM entry index page.

## Expected Behavior

After creating an entry or a DM entry, the user should be redirected to the campaign details page if they initially clicked on entry and DM entry buttons there.

## Steps to Reproduce

For Entry
1. Create a campaign with assigned character
2. Click on campaign (go to its detail page)
3. Create an entry and click create
4. You are now incorrectly redirected
For DM Entry
1. Create a campaign
2. Click on campaign (go to its detail page)
3. Create a DM entry and click create
4. You are now incorrectly redirected

## Possible Fix

# Other

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/500?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo
