### ISSUE TITLE
Backend Route Cleanup

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#502]
## Description

There are some routes that have been auto generated at the beginning of the project that have since not been used. These routes and controller functions should be removed so that malicious users cannot send requests to the endpoints.

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/502?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo
