### ISSUE TITLE
Accept: League Admin Event Control

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#504]
## Description
Acceptance Test for #363

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #439 for automation of this flow 

## Acceptance Flow

1. Log in to the admin account
2. navigate to the admin page via /admin
3. Navigate to the events page via the panel on the left
4. Attempt to create a league event
5. Verify that the event is created
6. Attempt to edit a league event
7. Verify that the changes you have made are saved to the event
8. Attempt to delete a league event.
9. Verify that the event is deleted.

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
