### ISSUE TITLE
Accept: Campaign Creation and Modification

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#505]
## Description
 Acceptance Test for #365

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #443 for automation of this flow

## Acceptance Flow

1. Log in as a regular user
2. Navigate to the campaigns page
3. Attempt to create a campaign
4. Verify that the campaign is created and that you are given a join code
5. Attempt to modify the campaign's details
6. Verify that the changes are saved

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
