### ISSUE TITLE
Accept: Player Event Registration

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#506]
## Description
Acceptance Test for #241

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #440 for automation of this flow

## Acceptance Flow

1. Log in as a regular user
2. Navigate to the events page
3. Select an event you wish to join
4. Fill out the event join form
5. Verify that you have been added to the event

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

ISSUE?: When I join the event, I see that my character is  listed under ‘Chosen Character’ but I can’t see it anywhere else. Like #509, maybe some extra text to say when it will show up?

-Kate Ruscito
