### ISSUE TITLE
Accept: Admin Session Control

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#507]
## Description
Acceptance Test for #242

Ability for admins to create and assign sessions to events.

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

## Acceptance Flow

1. Admin user Logs in
2. Admin navigates to backpack control panel (`/admin`)
3. Admin presses "Sessions" in the sidebar
4. Admin clicks "Add Session"
5. Admin fills out details for the session, and chooses an event its attached too
6. Admin clicks "Save"
7. Admin returns to Sessions Index in the Admin Panel
8. Admin clicks Edit on a Session of their choosing
9. Admin edits some information on the chosen Session
10. Admin clicks save

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
