### ISSUE TITLE
Accept: Campaign Enrollment

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#508]
## Description
Acceptance Test for #251

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #440 for automation of this flow

## Acceptance Flow

**Note:** Requires that a campaign exists and you have the join code. You may either create a new campaign on another account and copy the join code, or pick a join code from [a campaign in the admin panel](https://session-tome.triassi.ca/admin/campaign) that the user is not registered for. 
1. Log in as a regular user
2. Navigate to the campaign page
3. Open the campaign join form
4. Enter a campaign join code and submit the join form
5. Verify that you have been added to the campaign

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito
