### ISSUE TITLE
Accept: Open Session Entry Automation

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#509]
## Description
Acceptance Test for #364

Ability to have entries created automatically for a user, based off the start time of a session they are registered for

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

## Acceptance Flow

1. User Logs in
2. User navigates to the Event Page
3. User picks an event they'd like to register for
4. User clicks "register" on a particular Session and chooses a character
5. User waits for the start time for the session to pass
6. User observes a new entry created for that character

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

NOTE: I would probably add to the text that the event will show up in 15 minutes so people don’t think they didn’t mess up!

-Kate Ruscito
