### ISSUE TITLE
Accept: Campaign Entry Creation

### ISSUE THREAD

**Issue by m-triassi** [DnD-Montreal/session-tome#510]
## Description
Acceptance Test for #252 

The ability to create entries related to a campagin and have those entries automatically created for other users in your campagin

[UAT Environment](https://session-tome.triassi.ca) for executing the acceptance flow

See #445 for automation of this flow

## Acceptance Flow

1. User logs in
2. User joins a campaign or chooses one they are already registered for
3. User clicks the title of the campaign they've chosen to see the details of the campaign
4. User clicks the "Entry" button
5. User fills out the details for the entry
6. User clicks save
7. User observes that the entries were created for themselves as well as all users in their campaign
8. User creates a new campaign in which they are the DM
9. User navigates to the Campaign's detail screen by clicking it's title
10. User clicks "DM Entry" and creates an entry for the campaign
11. User observes that the entry was created for themselves as well as other characters in the campaign

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

-Kate Ruscito

**Comment by DndMtl** [comment]
Everything works perfectly! Approved!

NOTE: I would probably add to the text that the event will show up in 15 minutes so people don’t think they didn’t mess up!

-Kate Ruscito
