### ISSUE TITLE
Deleting Campaign with Ratings Throws Exception

### ISSUE THREAD

**Issue by JasonGadoury** [DnD-Montreal/session-tome#512]
## Description

Deleting a campaign that has dm ratings throws an exception

## Expected Behavior

Campaign should be deleted successfully 

## Actual Behavior

Query exception: integrity constraint violation is thrown

## Steps to Reproduce

1. Log in with test account
2. Create campaign, (choose "None" as character)
3. Logout of test account
4. Login with different user
5. Join the campaign created in step 2 with different user
6. Create an Entry within that campaign, including the submission of a dm rating
7. Log back in with user who created campaign
8. Delete campaign

## Context
Particular edge case for campaign deletion failing

## Possible Fix
Fix foreign key constraints between ratings, entries, and campaigns tables

# Other

## Additional Notes

![delete campaign exception.PNG](https://images.zenhubusercontent.com/61397158f402af5ddf78f60c/4cf1633e-458c-47cc-896b-8b56d60635b7)

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/512?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo
