### ISSUE TITLE
Remove "DM Entry" Button from Campaigns Joined as a Character

### ISSUE THREAD

**Issue by JasonGadoury** [DnD-Montreal/session-tome#514]
## Description
Campaigns joined with a character displays both DM Entry and Entry options. The user should not be able to see the DM Entry button nor be able to create one. Doing so results in both the creation of a DM entry and a regular entry.

## Expected Behavior
Only Entry button visible and accessible for campaigns joined with character.

## Actual Behavior

DM Entry button also visible and allows user to create DM Entry 

## Steps to Reproduce

1. Join an existing campaign with a character
2. Choose the campaign from index
3. From the campaign's page create DM Entry
4. A new entry could now be seen in the DM entries table as well as that character's entries

## Possible Fix

# Other

**Comment by willyyhuang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/514?planning-poker) with ZenHub @AnnieTran13 @luigibesani @pascwhale
