### ISSUE TITLE
DM entry creation bug

### ISSUE THREAD

**Issue by AnnieTran13** [DnD-Montreal/session-tome#519]
## Description

If a logged in user creates a campaign and assigns a character, when they create a DM entry and select the recently created campaign, then the campaign gets created and appears in the campaign entry table.

## Expected Behavior

The user should not be able to create the DM entry for a campaign where they are not the GM.

## Steps to Reproduce

1. Create campaign and assign character
2. Create DM entry and select the campaign
3. Return to campaign details page

## Possible Fix

Return an error in DMEntryCreate when user selects a campaign where they are not the GM.
OR
Filter the list of campaigns returned in DMEntryCreate in order to only return campaigns where they are GM

# Other

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/519?planning-poker) with ZenHub @bcobo341 @IanjhPhillips @JasonGadoury @RobertoNittolo
