### ISSUE TITLE
Multiple registration to the session not working

### ISSUE THREAD

**Issue by willyyhuang** [DnD-Montreal/session-tome#543]
## Description

When joining the same event with multiple instances of session, the 2nd registration does not seem to reflect on the front-end and the data passed by backend seems to be wrong as well.

## Expected Behavior

An user is able to join multiple sessions

## Actual Behavior

An user can only join one session in one event

**Comment by m-triassi** [comment]
Technically #555 is a duplicate of this card, since this was opened first, but #555 has more detail, so closing this as duplicate
