### ISSUE TITLE
Basic welcome page

### ISSUE THREAD

**Issue by willyyhuang** [DnD-Montreal/session-tome#59]
Home page should direct to this page
![image](https://user-images.githubusercontent.com/48188884/134439460-84073821-5ae0-4431-85ba-4e313980e5df.png)

UI Interactive Mockup links:

- [Home Page](https://www.figma.com/proto/5uF4bHcHFTm13iMyrBzMt0/Designs-and-Mockups?node-id=12%3A6&scaling=min-zoom&starting-point-node-id=405%3A24088&show-proto-sidebar=1)

**Comment by willyyhuang** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/59?planning-poker) with ZenHub @AnnieTran13 @bcobo341 @luigibesani

**Comment by willyyhuang** [comment]
maybe implement upcoming events in calendar form

**Comment by luigibesani** [comment]
Very nice design. The color theme is looking good. Having upcoming events on the home page is a great idea.
