### ISSUE TITLE
Implement logic for Store Item Endpoint

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#64]
## Description

Item should track the User who created it through an Author field. Also should verify the User's permissions before completing the request.

## Possible Implementation
* Add author field to model (Relation to user, add function on User class)
* Add author rule to ItemStoreRequest.php + ItemUpdateRequest.php
* Update authorize function in ItemStoreRequest.php to include permissions verification
* Add logic to Item Controller Store function
* Add author field to ItemFactory

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/64?planning-poker) with ZenHub @IanjhPhillips @JasonGadoury @pascwhale @RobertoNittolo
