### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#71]
## User story
As a user with an account, I should be able to log in to my account so that I can interact with the system through my account.

## Narrative
* The user navigates to the login form
* The user inputs their login info and submits the form
* The user's login info is verified and the user is logged in to their account
* The user is redirected to the main page

## Acceptance criteria

|#     |Given     |When     |Then|
|---|---|---|---|
|1 | I am a user | I navigate to the login page | I am presented with a form which receives my login credentials |
|2     | I am a user with an account    |  I input my valid login info  | I am logged in to my account and redirected from the login form |
|3     | I am a user   |  I input invalid login info   | I am not logged in and receive feedback that my login attempt has failed |

**Comment by m-triassi** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Session-Tome-613674a263226c0015d44c06/issues/DnD-Montreal/session-tome/71?planning-poker) with ZenHub @IanjhPhillips @willyyhuang @luigibesani

**Comment by IanjhPhillips** [comment]
I thought we weren't putting estimates on story level cards.
