### ISSUE TITLE
Assign Roles

### ISSUE THREAD

**Issue by IanjhPhillips** [DnD-Montreal/session-tome#72]
## User story
As an admin, I should be able to assign roles to other users so that I can manage their permissions within my league.

## Narrative
As an administrator it should be possible for me to assign roles to other users which grant or deny them permissions within the site.

## Acceptance criteria

|#     |Given     |When     |Then|
|---|---|---|---|
|1     |   I am a site super admin  |   I assign roles to users  | I should be unrestricted in which roles I can assign |
|2     |   I am a league admin  |   I assign roles to users  | I should be able to assign roles up to league admin level |
|3     |   I am a regular user | I attempt to assign roles to another user | My request should be denied |

**Comment by m-triassi** [comment]
This actually gets completely, if not mostly, solved by Laravel Backpack #221 @IanjhPhillips we should make 100% certain it does, though

**Comment by IanjhPhillips** [comment]
I believe it mostly handles it, however we'll need to make some adjustments if we wish to extend our system to allow users to create and manage their own leagues. I dont know if giving Users access to backpack is the best idea.
